---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - gateway.networking.k8s.io_backendtlspolicies.yaml
  - gateway.networking.k8s.io_gatewayclasses.yaml
  - gateway.networking.k8s.io_gateways.yaml
  - gateway.networking.k8s.io_grpcroutes.yaml
  - gateway.networking.k8s.io_httproutes.yaml
  - gateway.networking.k8s.io_referencegrants.yaml
  - gateway.networking.k8s.io_tcproutes.yaml
  - gateway.networking.k8s.io_tlsroutes.yaml
  - gateway.networking.k8s.io_udproutes.yaml
  - hub.traefik.io_accesscontrolpolicies.yaml
  - hub.traefik.io_apiaccesses.yaml
  - hub.traefik.io_apiportals.yaml
  - hub.traefik.io_apiratelimits.yaml
  - hub.traefik.io_apis.yaml
  - hub.traefik.io_apiversions.yaml
  - traefik.io_ingressroutes.yaml
  - traefik.io_ingressroutetcps.yaml
  - traefik.io_ingressrouteudps.yaml
  - traefik.io_middlewares.yaml
  - traefik.io_middlewaretcps.yaml
  - traefik.io_serverstransports.yaml
  - traefik.io_serverstransporttcps.yaml
  - traefik.io_tlsoptions.yaml
  - traefik.io_tlsstores.yaml
  - traefik.io_traefikservices.yaml
