stages:
  - build
  - test

variables:
  GO_VERSION: "1.22.4"

before_script:
  - echo "Using Go version $GO_VERSION"
  - curl -sSL https://golang.org/dl/go$GO_VERSION.linux-arm64.tar.gz | tar -C /usr/local -xz
  - export PATH=$PATH:/usr/local/go/bin

build:
  stage: build
  tags:
    - toolchench-arm64-osx-home
  script:
    - go mod tidy
    - go build -o kcl-mod-importer main.go

test:
  stage: test
  tags:
    - toolchench-arm64-osx-home
  script:
    - go test ./...
